param:
  # 克隆仓库目录
  repo_dir: '/Users/menghuawei/PycharmProjects/GitRepo/'
  # GIT仓库地址 默认使用GIT仓库地址
  git_repo_url: 'git@gitee.com:iewiewiew/test-demo-002.git'
  # HTTPS仓库地址
  https_repo_url: 'https://gitee.com/iewiewiew/test-demo-002.git'
  # 仓库名称
  repo_name: 'test-demo-002'

ci_env:
  param:
    # 克隆仓库目录
    repo_dir: '/Users/menghuawei/PycharmProjects/GitRepo/'
    # GIT仓库地址 默认使用GIT仓库地址
    git_repo_url: 'git@gitee.com:iewiewiew/test-demo-002.git'
    # HTTPS仓库地址
    https_repo_url: 'https://gitee.com/iewiewiew/test-demo-002.git'
    # 仓库名称
    repo_name: 'test-demo-002'

pro_env:
  param:
    # 克隆仓库目录
    repo_dir: '/Users/menghuawei/PycharmProjects/GitRepo/'
    # GIT仓库地址 默认使用GIT仓库地址
    git_repo_url: 'git@gitee.com:iewiewiew/test-demo-002.git'
    # HTTPS仓库地址
    https_repo_url: 'https://gitee.com/iewiewiew/test-demo-002.git'
    # 仓库名称
    repo_name: 'test-demo-002'